In [1]:
import polars as pl

/home/joshua.siedel/nas_home/hackathon/ClassyFridge/.venv/lib/python3.12/site-packages/polars/_cpu_check.py:271: RuntimeWarning: Missing required CPU features.

The following required CPU features were not detected:
    pclmulqdq
Continuing to use this version of Polars on this processor will likely result in a crash.
Install `polars[rtcompat]` instead of `polars` to run Polars with better compatibility.

Hint: If you are on an Apple ARM machine (e.g. M1) this is likely due to running Python under Rosetta.
It is recommended to install a native version of Python that does not run under Rosetta x86-64 emulation.

If you believe this warning to be a false positive, you can set the `POLARS_SKIP_CPU_CHECK` environment variable to bypass this check.

  warnings.warn(

In [2]:
df_train = pl.read_csv("./FungiTastic/metadata/FungiTastic-Mini/FungiTastic-Mini-Train_augmented.csv")
print(len(df_train))

81900

In [3]:
df_train.describe()

shape: (9, 33)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ eventDate ┆ year      ┆ month    ┆ … ┆ elevation ┆ landcover ┆ biogeogra ┆ captions  │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ phicalReg ┆ ---       │
│ str       ┆ str       ┆ f64       ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ion       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ ---       ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ str       ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 81900     ┆ 81900.0   ┆ 81900.0  ┆ … ┆ 81773.0   ┆ 81773.0   ┆ 81764     ┆ 81731     │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0      ┆ … ┆ 127.0     ┆ 127.0     ┆ 136       ┆ 169       │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ 2018.3374 ┆ 9.037143 ┆ … ┆ 70.241663 ┆ 11.605102 ┆ null      ┆ null      │
│           ┆           ┆ 24        ┆          ┆   ┆           ┆           ┆           ┆           │
│ std       ┆ null      ┆ 3.340515  ┆ 1.553591 ┆ … ┆ 144.99101 ┆ 5.528178  ┆ null      ┆ null      │
│           ┆           ┆           ┆          ┆   ┆ 4         ┆           ┆           ┆           │
│ min       ┆ 1963-08-1 ┆ 1963.0    ┆ 1.0      ┆ … ┆ 0.0       ┆ 1.0       ┆ alpine    ┆ The       │
│           ┆ 5         ┆           ┆          ┆   ┆           ┆           ┆           ┆ basket    │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ contains  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ a diverse │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ …         │
│ 25%       ┆ null      ┆ 2017.0    ┆ 8.0      ┆ … ┆ 0.0       ┆ 8.0       ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ 2019.0    ┆ 9.0      ┆ … ┆ 13.0      ┆ 12.0      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ 2021.0    ┆ 10.0     ┆ … ┆ 74.0      ┆ 17.0      ┆ null      ┆ null      │
│ max       ┆ 2021-12-3 ┆ 2021.0    ┆ 12.0     ┆ … ┆ 2313.0    ┆ 17.0      ┆ pannonian ┆ The tree  │
│           ┆ 1         ┆           ┆          ┆   ┆           ┆           ┆           ┆ trunk is  │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ adorned   │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ with…     │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df_val = pl.read_csv("./FungiTastic/metadata/FungiTastic-Mini/FungiTastic-Mini-Val.csv")
print(len(df_val))

9412

In [5]:
df_val.describe()

shape: (9, 30)
┌────────────┬────────────┬────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ eventDate  ┆ year   ┆ month    ┆ … ┆ category_i ┆ metaSubst ┆ poisonous ┆ captions  │
│ ---        ┆ ---        ┆ ---    ┆ ---      ┆   ┆ d          ┆ rate      ┆ ---       ┆ ---       │
│ str        ┆ str        ┆ f64    ┆ f64      ┆   ┆ ---        ┆ ---       ┆ f64       ┆ str       │
│            ┆            ┆        ┆          ┆   ┆ f64        ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 9412       ┆ 9412.0 ┆ 9412.0   ┆ … ┆ 9412.0     ┆ 9412      ┆ 9412.0    ┆ 9391      │
│ null_count ┆ 0          ┆ 0.0    ┆ 0.0      ┆ … ┆ 0.0        ┆ 0         ┆ 0.0       ┆ 21        │
│ mean       ┆ null       ┆ 2022.0 ┆ 9.249788 ┆ … ┆ 88.196345  ┆ null      ┆ 0.185083  ┆ null      │
│ std        ┆ null       ┆ 0.0    ┆ 1.569613 ┆ … ┆ 62.873816  ┆ null      ┆ 0.388385  ┆ null      │
│ min        ┆ 2022-01-01 ┆ 2022.0 ┆ 1.0      ┆ … ┆ 1.0        ┆ animals   ┆ 0.0       ┆ The       │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ basket    │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ contains  │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ a diverse │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ …         │
│ 25%        ┆ null       ┆ 2022.0 ┆ 9.0      ┆ … ┆ 35.0       ┆ null      ┆ 0.0       ┆ null      │
│ 50%        ┆ null       ┆ 2022.0 ┆ 10.0     ┆ … ┆ 78.0       ┆ null      ┆ 0.0       ┆ null      │
│ 75%        ┆ null       ┆ 2022.0 ┆ 10.0     ┆ … ┆ 144.0      ┆ null      ┆ 0.0       ┆ null      │
│ max        ┆ 2022-12-31 ┆ 2022.0 ┆ 12.0     ┆ … ┆ 214.0      ┆ wood      ┆ 1.0       ┆ The jar   │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ contains  │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ a variety │
│            ┆            ┆        ┆          ┆   ┆            ┆           ┆           ┆ of …      │
└────────────┴────────────┴────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
print(f"Poisonous mushrooms : {len(df_train.filter(pl.col("poisonous") == True))}")
print(f"Safe mushrooms      : {len(df_train.filter(pl.col("poisonous") == False))}")

Poisonous mushrooms : 40901

Safe mushrooms      : 40999

In [7]:
print(f"Poisonous mushrooms : {len(df_val.filter(pl.col("poisonous") == True))}")
print(f"Safe mushrooms      : {len(df_val.filter(pl.col("poisonous") == False))}")

Poisonous mushrooms : 1742
Safe mushrooms      : 7670

# Explorer le dataset de test

In [8]:
df_test = pl.read_csv("./FungiTastic/metadata/FungiTastic-Mini/FungiTastic-Mini-Test.csv")
df_test.head(10)

shape: (10, 29)
┌────────────┬────────┬───────┬──────┬───┬─────────────┬───────────────┬───────────┬───────────────┐
│ eventDate  ┆ year   ┆ month ┆ day  ┆ … ┆ category_id ┆ metaSubstrate ┆ poisonous ┆ captions      │
│ ---        ┆ ---    ┆ ---   ┆ ---  ┆   ┆ ---         ┆ ---           ┆ ---       ┆ ---           │
│ str        ┆ f64    ┆ f64   ┆ f64  ┆   ┆ i64         ┆ str           ┆ i64       ┆ str           │
╞════════════╪════════╪═══════╪══════╪═══╪═════════════╪═══════════════╪═══════════╪═══════════════╡
│ 2023-01-01 ┆ 2023.0 ┆ 1.0   ┆ 1.0  ┆ … ┆ 94          ┆ wood          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows a       │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ cluster of s… │
│ 2023-01-01 ┆ 2023.0 ┆ 1.0   ┆ 1.0  ┆ … ┆ 79          ┆ plant         ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆ material      ┆           ┆ shows three   │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct…     │
│ 2023-01-01 ┆ 2023.0 ┆ 1.0   ┆ 1.0  ┆ … ┆ 79          ┆ plant         ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆ material      ┆           ┆ shows three   │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct…     │
│ 2023-01-04 ┆ 2023.0 ┆ 1.0   ┆ 4.0  ┆ … ┆ 50          ┆ jord          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows three   │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct…     │
│ 2023-01-06 ┆ 2023.0 ┆ 1.0   ┆ 6.0  ┆ … ┆ 104         ┆ wood          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows a       │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ variety of f… │
│ 2023-01-06 ┆ 2023.0 ┆ 1.0   ┆ 6.0  ┆ … ┆ 104         ┆ wood          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows several │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ mushro…       │
│ 2023-01-06 ┆ 2023.0 ┆ 1.0   ┆ 6.0  ┆ … ┆ 104         ┆ wood          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows two     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ prominent …   │
│ 2023-01-07 ┆ 2023.0 ┆ 1.0   ┆ 7.0  ┆ … ┆ 104         ┆ wood          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows several │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ small …       │
│ 2023-01-07 ┆ 2023.0 ┆ 1.0   ┆ 7.0  ┆ … ┆ 104         ┆ wood          ┆ 0         ┆ The fungi in  │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ the image are │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ sma…          │
│ 2023-01-10 ┆ 2023.0 ┆ 1.0   ┆ 10.0 ┆ … ┆ 50          ┆ jord          ┆ 0         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows a       │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ single mushr… │
└────────────┴────────┴───────┴──────┴───┴─────────────┴───────────────┴───────────┴───────────────┘

In [9]:
df_test.filter(pl.col("poisonous") == 1).head(10)

shape: (10, 29)
┌────────────┬────────┬───────┬──────┬───┬─────────────┬───────────────┬───────────┬───────────────┐
│ eventDate  ┆ year   ┆ month ┆ day  ┆ … ┆ category_id ┆ metaSubstrate ┆ poisonous ┆ captions      │
│ ---        ┆ ---    ┆ ---   ┆ ---  ┆   ┆ ---         ┆ ---           ┆ ---       ┆ ---           │
│ str        ┆ f64    ┆ f64   ┆ f64  ┆   ┆ i64         ┆ str           ┆ i64       ┆ str           │
╞════════════╪════════╪═══════╪══════╪═══╪═════════════╪═══════════════╪═══════════╪═══════════════╡
│ 2023-07-13 ┆ 2023.0 ┆ 7.0   ┆ 13.0 ┆ … ┆ 24          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows two     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ prominent …   │
│ 2023-07-15 ┆ 2023.0 ┆ 7.0   ┆ 15.0 ┆ … ┆ 35          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows two     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ mushrooms …   │
│ 2023-07-15 ┆ 2023.0 ┆ 7.0   ┆ 15.0 ┆ … ┆ 35          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows a       │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ single mushr… │
│ 2023-07-15 ┆ 2023.0 ┆ 7.0   ┆ 15.0 ┆ … ┆ 35          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows a       │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ single mushr… │
│ 2023-07-24 ┆ 2023.0 ┆ 7.0   ┆ 24.0 ┆ … ┆ 30          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows two     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct f…   │
│ 2023-07-24 ┆ 2023.0 ┆ 7.0   ┆ 24.0 ┆ … ┆ 30          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows three   │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct…     │
│ 2023-07-25 ┆ 2023.0 ┆ 7.0   ┆ 25.0 ┆ … ┆ 35          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows two     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct f…   │
│ 2023-07-25 ┆ 2023.0 ┆ 7.0   ┆ 25.0 ┆ … ┆ 19          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows three   │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct…     │
│ 2023-07-26 ┆ 2023.0 ┆ 7.0   ┆ 26.0 ┆ … ┆ 24          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows several │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ white …       │
│ 2023-07-26 ┆ 2023.0 ┆ 7.0   ┆ 26.0 ┆ … ┆ 24          ┆ jord          ┆ 1         ┆ The image     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ shows two     │
│            ┆        ┆       ┆      ┆   ┆             ┆               ┆           ┆ distinct f…   │
└────────────┴────────┴───────┴──────┴───┴─────────────┴───────────────┴───────────┴───────────────┘